export const SELECT_PROJECT = 'SELECT_PROJECT';
export const LOADING_USER = 'LOADING_USER';
export const USER_LOADED = 'USER_LOADED';
export const USER_LOAD_ERROR = 'USER_LOAD_ERROR';
export const LOADING_PROJECTS = 'LOADING_PROJECTS';
export const PROJECTS_LOADED = 'PROJECTS_LOADED';
export const PROJECTS_LOAD_ERROR = 'PROJECTS_LOAD_ERROR';
